version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Uncomment to add PostgreSQL database
  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=rxreader
  #     - POSTGRES_PASSWORD=rxreaderpassword
  #     - POSTGRES_DB=rxreader
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U rxreader"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

# Uncomment to add volumes for PostgreSQL data
# volumes:
#   postgres_data: